server.port=8080
spring.application.name=gateway-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway Routes
spring.cloud.gateway.mvc.routes[0].id=passenger-service
spring.cloud.gateway.mvc.routes[0].uri=lb://PASSENGER-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/passengers/**

spring.cloud.gateway.mvc.routes[1].id=ride-service
spring.cloud.gateway.mvc.routes[1].uri=lb://RIDE-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/rides/**
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-methods=*
